// <auto-generated />
using System;
using HdProduction.Dashboard.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HdProduction.Dashboard.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190624153603_defaultAdmin")]
    partial class defaultAdmin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HdProduction.Dashboard.Domain.Entities.Builds.ProjectBuild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2019, 6, 24, 15, 36, 3, 486, DateTimeKind.Utc).AddTicks(5845));

                    b.Property<string>("LinkToDownload")
                        .HasMaxLength(512);

                    b.Property<long>("ProjectId");

                    b.Property<int?>("SelfHostConfiguration");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("project_build");
                });

            modelBuilder.Entity("HdProduction.Dashboard.Domain.Entities.Projects.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DefaultAdminSettings")
                        .HasColumnType("Json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("SelfHostSettings")
                        .HasColumnType("Json");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("project");
                });

            modelBuilder.Entity("HdProduction.Dashboard.Domain.Entities.Relational.UserProjectRights", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("ProjectId");

                    b.Property<int>("Right");

                    b.HasKey("UserId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("user_project");
                });

            modelBuilder.Entity("HdProduction.Dashboard.Domain.Entities.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("PwdSalt")
                        .IsFixedLength(true)
                        .HasMaxLength(32);

                    b.Property<string>("RefreshToken")
                        .IsFixedLength(true)
                        .HasMaxLength(44);

                    b.Property<string>("SaltedPwd")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("HdProduction.Dashboard.Domain.Entities.Builds.ProjectBuild", b =>
                {
                    b.HasOne("HdProduction.Dashboard.Domain.Entities.Projects.Project", "Project")
                        .WithMany("Builds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HdProduction.Dashboard.Domain.Entities.Relational.UserProjectRights", b =>
                {
                    b.HasOne("HdProduction.Dashboard.Domain.Entities.Projects.Project", "Project")
                        .WithMany("UserRights")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HdProduction.Dashboard.Domain.Entities.Users.User", "User")
                        .WithMany("ProjectRights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
